import { PrismaClient } from "@prisma/client";

export default async function seedRanks(prisma: PrismaClient) {
  console.log('Seeding ranks...');
  const ranks = [
    {
      name: 'Blue Safire',
      slug: 'blue-safire',
      min_direct_members: 3,
      min_indirect_members: 0,
      min_turnover: 3000,
      order: 1,
      cumulative_percent: 5.0,
      max_turnover_per_leg: 1000,
    },
    {
      name: 'Red Ruby',
      slug: 'red-ruby',
      min_direct_members: 4,
      min_indirect_members: 5,
      min_turnover: 6000,
      order: 2,
      cumulative_percent: 10.0,
      max_turnover_per_leg: 2500,
    },
    {
      name: 'Grenn Smaragd',
      slug: 'green-smaragd',
      min_direct_members: 4,
      min_indirect_members: 10,
      min_turnover: 12000,
      order: 3,
      cumulative_percent: 20.0,
      max_turnover_per_leg: 5000,
    },
    {
      name: 'Diamond',
      slug: 'diamond',
      min_direct_members: 5,
      min_indirect_members: 25,
      min_turnover: 25000,
      order: 4,
      cumulative_percent: 30.0,
      max_turnover_per_leg: 10000,
    },
    {
      name: 'Green Diamond',
      slug: 'green-diamond',
      min_direct_members: 5,
      min_indirect_members: 50,
      min_turnover: 50000,
      order: 5,
      cumulative_percent: 40.0,
      max_turnover_per_leg: 25000,
    },
    {
      name: 'Pink Diamond',
      slug: 'pink-diamond',
      min_direct_members: 5,
      min_indirect_members: 150,
      min_turnover: 1000000,
      order: 6,
      cumulative_percent: 50.0,
      max_turnover_per_leg: 50000,
    },
    {
      name: 'Red Diamond',
      slug: 'red-diamond',
      min_direct_members: 6,
      min_indirect_members: 150,
      min_turnover: 250000,
      order: 7,
      cumulative_percent: 50.0,
      max_turnover_per_leg: 50000,
    },
    {
      name: 'Blue Diamond',
      slug: 'blue-diamond',
      min_direct_members: 6,
      min_indirect_members: 150,
      min_turnover: 500000,
      order: 8,
      cumulative_percent: 50.0,
      max_turnover_per_leg: 50000,
    },
    {
      name: 'Black Diamond',
      slug: 'black-diamond',
      min_direct_members: 7,
      min_indirect_members: 150,
      min_turnover: 1000000,
      order: 9,
      cumulative_percent: 50.0,
      max_turnover_per_leg: 50000,
    },
    {
      name: 'Crow Diamond',
      slug: 'crow-diamond',
      min_direct_members: 7,
      min_indirect_members: 150,
      min_turnover: 2500000,
      order: 10,
      cumulative_percent: 50.0,
      max_turnover_per_leg: 50000,
    },
    {
      name: 'Crow President',
      slug: 'crow-president',
      min_direct_members: 8,
      min_indirect_members: 150,
      min_turnover: 5000000,
      order: 11,
      cumulative_percent: 50.0,
      max_turnover_per_leg: 50000,
    },
    {
      name: 'Crown Ambassador',
      slug: 'crown-ambassador',
      min_direct_members: 8,
      min_indirect_members: 150,
      min_turnover: 15000000,
      order: 12,
      cumulative_percent: 50.0,
      max_turnover_per_leg: 50000,
    },
  ];

  for (const rank of ranks) {
    await prisma.rank.upsert({
      where: { slug: rank.slug },
      update: {},
      create: rank,
    });
    console.log(`✓ Seeded rank: ${rank.name} (${rank.slug}) - Order: ${rank.order}`);
  }
  console.log('Seed completed successfully!');
}